INSERT INTO movies
	(title,rating,description,runtime_mins,created_at,updated_at)
VALUES
	('movie A','A','what ever',130,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	('movie B','B','what ever',130,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	('movie C','C','what ever',130,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO screenings
	(movie_id,screen_number,starts_at,capacity,created_at,updated_at)
VALUES
	(1 ,1, '2023-07-07 19:00:00',50,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	(1 ,7, '2023-07-07 20:00:00',20,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	(1 ,2, '2023-07-08 18:00:00',30,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	(2 ,1, '2023-07-15 22:05:15',10,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	(2 ,5, '2023-07-15 21:05:15',15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	(3 ,6, '2023-07-15 21:05:15',70,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	(3 ,9, '2023-07-15 21:05:15',60,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO customers
	(name,email,phone,created_at,updated_at)
VALUES
	('Customer A','customer_A@emailcom','+123456',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	('Customer B','customer_B@emailcom','+123456',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	('customer C','customer_C@emailcom','+123456',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	('customer D','customer_D@emailcom','+123456',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	('Custoemr E','customer_E@emailcom','+123456',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO tickets
	(customer_id,screening_id,num_seats,created_at,updated_at)
VALUES
	(1,2,3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	(1,2,4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	(1,2,6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	(1,7,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	(2,2,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	(2,3,3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	(2,3,5,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	(3,5,4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	(4,3,5,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	(4,6,3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	(5,3,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);