INSERT INTO ticket (id, created_at, updated_at, num_seats, screening_id, customer_id)
VALUES
    (1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3, 1, 1),
    (2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 1, 1),
    (3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, 1),
    (4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5, 2, 1),
    (5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3, 2, 1),
    (6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 3, 2),
    (7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 3, 2),
    (8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3, 3, 2),
    (9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3, 1, 2),
    (10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3, 1, 2);